export const navigationData=[
    {
        navItemName:"Home",
        route:"/"
    },
    {
        navItemName:"About",
        route:"/about"
    },
    {
        navItemName:"Timeline",
        route:"/timeline"
    }
    ,
    {
        navItemName:"Blog",
        route:"/blog"
    }
]